'use client';

import { useCallback, useEffect, useState } from 'react';
import api from '@/services/axios';
import { useAuth } from '@/context/AuthContext';

type Item={poiSqno:number;title:string;addr?:string;artist?:string;recommendReason?:string;source:string;sourceUrl:string;reviewStatus:string};
type Envelope<T>={data:T}; const sample:Item[]=[{poiSqno:101,title:'서울숲 K-POP 촬영 포인트',addr:'서울 성동구',artist:'K-POP 아티스트',recommendReason:'공개 출처로 촬영 사실을 확인한 팬 추천 장소입니다.',source:'UGC',sourceUrl:'https://example.com/source',reviewStatus:'PENDING'}];
function unwrap<T>(p:Envelope<T>|T):T{return p&&typeof p==='object'&&'data' in p?(p as Envelope<T>).data:p as T}
export default function HolyReviewPage(){const{user,isLoading}=useAuth();const[items,setItems]=useState<Item[]>([]);const[demo,setDemo]=useState(false);const[busy,setBusy]=useState<number|null>(null);
 const load=useCallback(async()=>{if(user?.role!=='ROLE_ADMIN')return;try{const r=await api.get<Envelope<Item[]>|Item[]>('/api/admin/tour/holy/pending');setItems(unwrap(r.data));setDemo(false)}catch{setItems(sample);setDemo(true)}},[user?.role]);useEffect(()=>{void load()},[load]);
 const review=async(id:number,action:'APPROVE'|'REJECT')=>{setBusy(id);try{await api.post(`/api/admin/tour/holy/${id}/review`,{action});setItems(v=>v.filter(x=>x.poiSqno!==id))}finally{setBusy(null)}};
 if(isLoading)return <main className="min-h-screen bg-[#f6f7f9] p-8">불러오는 중…</main>;
 return <main className="min-h-screen bg-[#f6f7f9] px-5 py-8 text-[#15171a] md:px-10"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold tracking-[.16em] text-red-600">KRIDE ADMIN</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">성지 제보 검수</h1><p className="mt-2 text-sm text-gray-500">출처와 사실 정보를 확인한 뒤 공개 여부를 결정합니다.</p></div><span className="rounded-full bg-white px-4 py-2 text-sm font-semibold shadow-sm">대기 {items.length}건</span></div>{demo&&<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">관리자 세션이 없어 검수 화면 예시를 표시합니다.</p>}<section className="mt-7 grid gap-4">{items.map(x=><article key={x.poiSqno} className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><div className="flex gap-2"><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">{x.source}</span><span className="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold">{x.reviewStatus}</span></div><h2 className="mt-3 text-xl font-bold">{x.title}</h2><p className="mt-1 text-sm text-gray-500">{x.addr} · {x.artist}</p><p className="mt-4 text-sm leading-6">{x.recommendReason}</p><a className="mt-3 block text-sm font-semibold text-blue-700 underline" href={x.sourceUrl} target="_blank" rel="noreferrer">출처 확인</a></div><div className="flex items-end gap-2"><button disabled={busy===x.poiSqno||demo} onClick={()=>void review(x.poiSqno,'REJECT')} className="rounded-xl border px-5 py-3 text-sm font-bold disabled:opacity-40">반려</button><button disabled={busy===x.poiSqno||demo} onClick={()=>void review(x.poiSqno,'APPROVE')} className="rounded-xl bg-red-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-40">승인·공개</button></div></div></article>)}{items.length===0&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-gray-500">검수 대기 제보가 없습니다.</div>}</section></div></main>}
