const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..');
const app='subproject/SDUI/metadata-project/';
const git=(...args)=>execFileSync('git',args,{cwd:root,encoding:'utf8'}).trim();
const base='1c40459045bd9b8c02a85db73902f8b895e7a821';
const snippets=[
 ['시간 카드','app/styles/pages.css','.time-card {','부모 너비를 채우고 긴 요약은 한 줄로 표시합니다.'],
 ['검색·필터·선택','components/plugins/travel/TourExploreScreen.tsx','const filteredPois','검색은 불러온 목록에만 적용합니다. 지역·정렬·작품 조건과 목록/지도 선택을 같은 화면이 관리합니다.'],
 ['지도 연결','components/plugins/travel/TourExploreMap.tsx','export function hasTourCoordinates','mapX는 경도, mapY는 위도입니다. 유효 좌표만 핀을 만들고 선택 시 카드로 초점을 옮깁니다.'],
 ['SDK 재시도','components/fields/kride/maps/loadKakaoMaps.ts','const fail =','실패한 스크립트를 제거하고 Promise를 초기화해 다시 로드할 수 있습니다.'],
 ['회귀 테스트','tests/components/TourExploreScreen.test.tsx',"it('일반 장소와 성지 오류",'오류 출처, 재시도, 페이지 응답 순서, 검색과 선택 연결을 검증합니다.'],
];
function snippet(text,needle){const lines=text.split(/\r?\n/);const start=Math.max(0,lines.findIndex(line=>line.includes(needle)));return lines.slice(start,start+24).map((line,i)=>`${start+i+1}  ${line}`).join('\n');}
const nodes=snippets.map(([title,file,needle,description])=>{
 let before='기준 main에 없는 새 파일';try{before=snippet(git('show',`${base}:${app+file}`),needle)}catch{}
 return {title,path:app+file,description,before,after:snippet(fs.readFileSync(path.join(root,app+file),'utf8'),needle)};
});
const read=name=>JSON.parse(fs.readFileSync(path.join(__dirname,name),'utf8'));
const tests=read('final-tests.json');
const api=read('public-api-read-check.json');
const captures={};
for(const width of [360,390,768,960,1440]){
 captures[width]={};for(const phase of ['baseline','after']) {const file=path.join(__dirname,phase,`${width}.png`);if(fs.existsSync(file)) captures[width][phase]='data:image/png;base64,'+fs.readFileSync(file).toString('base64');}
}
const evidence=fs.existsSync(path.join(__dirname,'after/evidence.json'))?read('after/evidence.json'):[];
const data={base,head:git('rev-parse','HEAD'),branch:git('branch','--show-current'),nodes,tests:{passed:tests.numPassedTests,failed:tests.numFailedTests,suites:tests.numPassedTestSuites},api,captures,evidence,history:git('log','--oneline',`${base}..HEAD`)};
const html=`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>KMovement 탐색 UI 구현·검증 보고서</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f4f6f8;color:#1c293a;font:15px/1.7 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:28px}h1{font-size:32px;line-height:1.3}h2{font-size:21px}button,select{font:inherit;cursor:pointer;padding:10px 14px;border:1px solid #c4ccd7;border-radius:9px;background:white;color:#263244}button:focus-visible,select:focus-visible{outline:3px solid #b31d38;outline-offset:3px}.hero,.panel{background:white;border:1px solid #dce1e8;border-radius:16px;padding:24px;margin-bottom:20px}.eyebrow{color:#9d1d36;font-weight:bold}.summary,.flow,.compare{display:grid;gap:12px;grid-template-columns:repeat(4,1fr)}.summary div{padding:14px;background:#f2f5f8;border-radius:12px}.flow{grid-template-columns:repeat(6,1fr);margin-bottom:20px}.flow button{border-top:4px solid #277b58}.flow button:last-child{border-color:#ba7b23}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}[aria-selected=true],[aria-pressed=true]{background:#fbecef;border-color:#af2141}.map{display:grid;grid-template-columns:minmax(240px,1fr) minmax(0,1.5fr);gap:22px}.nodes{display:grid;gap:12px}.nodes button{text-align:left}.nodes button:last-child{border-style:dashed}pre{background:#172335;color:#e7edf4;overflow:auto;padding:16px;border-radius:10px;font:12px/1.6 monospace;max-height:420px;white-space:pre}p{max-width:80ch}small{color:#556273}.compare{grid-template-columns:1fr 1fr}.compare img{width:100%;height:auto;border:1px solid #ddd}.compare figure{margin:0}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #dce1e8;padding:12px;vertical-align:top}details{padding:12px 0}[hidden]{display:none!important}.flow button[aria-current=step]{outline:2px solid #9d1d36}@media(max-width:760px){main{padding:12px}.hero,.panel{padding:16px}.map,.compare{grid-template-columns:1fr}.summary,.flow{grid-template-columns:repeat(2,1fr)}h1{font-size:25px}}</style>
<main><header class="hero"><span class="eyebrow">KMovement · 2026-10-05 · 구현 및 검증</span><h1>탐색 화면에서 장소를 찾고<br>카드와 지도 사이를 이동하기</h1><p>시간 카드 반응형, 검색·필터, 카드↔핀 선택, 조회 경로별 복구 행동을 단계별 커밋으로 정리했습니다.</p><div class="summary"><div><strong>구현</strong><p>시간 → 필터 → 지도 → 오류 복구</p></div><div><strong>자동 테스트</strong><p id="test-summary"></p></div><div><strong>검증 화면</strong><p>360 / 390 / 768 / 960 / 1440px</p></div><div><strong>다음 행동</strong><p>브랜치 검토 후 병합·배포 승인</p></div></div><details><summary>기준 브랜치와 검증 범위</summary><pre id="revision"></pre><p>변경 전 캡처는 현재 운영 웹에 브라우저 내부에서만 예시 응답을 주입한 화면입니다. 해당 배포의 정확한 이미지 SHA는 이번에 재확인하지 않았습니다. 변경 후는 로컬 구현을 같은 예시 데이터로 캡처했습니다. 운영 API는 별도 GET 검증입니다.</p></details></header>
<nav class="flow" aria-label="진행 단계"><button data-step="0">1 기준선 · 완료</button><button data-step="0">2 시간 카드 · 완료</button><button data-step="1">3 검색·필터 · 완료</button><button data-step="2">4 카드↔지도 · 완료</button><button data-step="3">5 복구·검증</button><button data-step="4" aria-current="step">6 사용자 검토</button></nav>
<section class="panel"><div class="tabs" role="tablist" aria-label="보고서 탭"><button role="tab" id="tab-map" aria-controls="map" aria-selected="true">코드·작업 지도</button><button role="tab" id="tab-screen" aria-controls="screen" aria-selected="false" tabindex="-1">화면 비교</button><button role="tab" id="tab-check" aria-controls="check" aria-selected="false" tabindex="-1">검증·배포</button><button role="tab" id="tab-history" aria-controls="history" aria-selected="false" tabindex="-1">근거·이력</button></div>
<div role="tabpanel" id="map" aria-labelledby="tab-map"><div class="map"><div><h2>화면 → 선택 상태 → 지도</h2><p>필터와 검색 결과가 카드·지도에 함께 전달됩니다. 핀의 ID를 선택 상태로 돌려주면 해당 카드가 강조되고 초점이 이동합니다.</p><div class="nodes" id="nodes"></div></div><article><h2 id="detail-title" tabindex="-1"></h2><small id="path"></small><p id="description"></p><div><button id="before" aria-pressed="false">기준 코드</button> <button id="after" aria-pressed="true">수정 코드</button></div><pre id="code"></pre><small>숫자는 해당 파일의 실제 줄 번호입니다. 새 파일에는 기준 코드가 없습니다.</small></article></div></div>
<div role="tabpanel" id="screen" aria-labelledby="tab-screen" hidden><h2>실제 브라우저 캡처</h2><p>기준선에서 360~960px 시간 카드 텍스트 폭은 약 18~19px로 측정됐습니다. 화면 전체의 가로 넘침과 수정 후 본문 폭을 자동 검사합니다.</p><label>화면 폭 <select id="width"><option>360</option><option>390</option><option>768</option><option selected>960</option><option>1440</option></select></label><div class="compare"><figure><h3>Before · 운영 UI + 예시 API</h3><img id="before-image" alt="변경 전 화면"></figure><figure><h3>After · 로컬 UI + 예시 API</h3><img id="after-image" alt="변경 후 화면"></figure></div></div>
<div role="tabpanel" id="check" aria-labelledby="tab-check" hidden><h2>확인한 결과와 남은 범위</h2><table><thead><tr><th>항목</th><th>결과 / 판단 기준</th></tr></thead><tbody><tr><td>시간 카드</td><td>5개 폭의 실제 캡처·본문 너비·문서 가로 넘침 확인</td></tr><tr><td>검색과 필터</td><td>이름·주소 검색, 지역 변경, 초기화. 검색은 불러온 결과에만 적용</td></tr><tr><td>카드↔지도</td><td>좌표 순서, 유효 범위, 클릭 이벤트, 강조, 초점 복귀, 이벤트 정리 자동 테스트. 브라우저 핀 검증은 SDK 테스트 대역을 사용</td></tr><tr><td>오류 복구</td><td>일반 장소 조회 / 성지 조회 / 지도 SDK / 지역 / 작품 검색의 재시도 분리. 특정 DB 자체 장애로 단정하지 않음</td></tr><tr><td>실제 지도 SDK</td><td>로컬에서는 SDK 연결 실패 화면을 확인. 실제 승인 도메인에서 새 구현의 카카오 타일·핀 동작은 배포 후 별도 확인 필요</td></tr><tr><td>운영 API</td><td>공개 GET 4종. 맛집 최초 25초 시간 초과 후 재조회 200. 성지 300곳, 관광지 3곳, 지역 17개</td></tr><tr><td>배포 및 DB</td><td>main 병합·운영 배포 미실행. ChromaDB·pgvector 연결 및 DB 변경 없음</td></tr></tbody></table><details><summary>브라우저 측정 원문</summary><pre id="browser-evidence"></pre></details><details><summary>운영 API 읽기 검증</summary><pre id="api"></pre></details></div>
<div role="tabpanel" id="history" aria-labelledby="tab-history" hidden><h2>독립 커밋과 실행 순서</h2><pre id="commits"></pre><p>검토 시 시간 카드 → 검색·필터 → 지도 → 복구 커밋 순서로 비교할 수 있습니다. 공개 API 읽기는 이 브랜치의 배포 성공을 의미하지 않습니다.</p><details><summary>배포 승인 후 실행할 검증</summary><ol><li>승인된 main SHA와 이미지 digest, 설정 revision, rollback digest를 같은 기록에 남깁니다.</li><li>기존 웹 이미지 교체 후 실제 도메인에서 카카오 SDK가 초기화되는지 확인합니다.</li><li>카드 선택 → 지도 이동 → 핀 선택 → 카드 강조·초점 복귀를 실제 데이터로 검증합니다.</li><li>5개 화면 폭과 실패·재시도 동작을 다시 확인합니다.</li></ol></details></div></section></main>
<script id="data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script>
const data=JSON.parse(document.getElementById('data').textContent);let selected=0,mode='after';const byId=id=>document.getElementById(id);const tabs=Array.from(document.querySelectorAll('[role=tab]'));function activate(id){tabs.forEach(t=>{const active=t.getAttribute('aria-controls')===id;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;byId(t.getAttribute('aria-controls')).hidden=!active;});}tabs.forEach((tab,i)=>{tab.onclick=()=>activate(tab.getAttribute('aria-controls'));tab.onkeydown=e=>{let next=i;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();activate(tabs[next].getAttribute('aria-controls'));tabs[next].focus();};});function render(focus=false){const node=data.nodes[selected];byId('detail-title').textContent=node.title;byId('path').textContent=node.path;byId('description').textContent=node.description;byId('code').textContent=node[mode];byId('before').setAttribute('aria-pressed',String(mode==='before'));byId('after').setAttribute('aria-pressed',String(mode==='after'));document.querySelectorAll('[data-node]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.node)===selected)));if(focus){byId('detail-title').scrollIntoView({block:'nearest'});byId('detail-title').focus();}}data.nodes.forEach((node,i)=>{const b=document.createElement('button');b.textContent=node.title;b.dataset.node=i;b.onclick=()=>{selected=i;render(true);};byId('nodes').append(b);});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{selected=Number(b.dataset.step);activate('map');render(true);});for(const m of ['before','after'])byId(m).onclick=()=>{mode=m;render();};function showImages(){const images=data.captures[byId('width').value];for(const p of ['before','after']){const src=images[p==='before'?'baseline':'after'];if(src)byId(p+'-image').src=src;}}byId('width').onchange=showImages;byId('test-summary').textContent=data.tests.passed+'개 통과 / '+data.tests.failed+'개 실패';byId('revision').textContent='기준 '+data.base+'\\n브랜치 '+data.branch+'\\n구현 HEAD '+data.head;byId('browser-evidence').textContent=JSON.stringify(data.evidence,null,2);byId('api').textContent=JSON.stringify(data.api,null,2);byId('commits').textContent=data.history;render();showImages();</script></html>`;
const name='work-map-20261005-'+new Date(Date.now()+9*3600000).toISOString().replace(/\D/g,'').slice(8,14)+'-tour-explore.html';
fs.writeFileSync(path.join(root,'work-map-guide',name),html);
console.log(path.join(root,'work-map-guide',name));
