-- K-POP artist catalog expansion so the explore page can render the same
-- artist options that appear on the holy submission form.

INSERT INTO artist (slug, name_ko, name_en, profile, image_url, official_url, sort_order)
VALUES
('BTS', 'BTS', 'BTS', 'Global K-POP artist with Seoul travel demand.', NULL, 'https://ibighit.com/bts', 1),
('BLACKPINK', 'BLACKPINK', 'BLACKPINK', 'K-POP artist connected to pop-up, fashion, and concert routes.', NULL, 'https://www.ygfamily.com', 2),
('SEVENTEEN', 'SEVENTEEN', 'SEVENTEEN', 'Performance-focused K-POP artist for event-led routes.', NULL, 'https://www.pledis.co.kr', 3),
('IVE', 'IVE', 'IVE', 'Trend-forward K-POP artist for fan travel discovery.', NULL, 'https://www.starship-ent.com', 4),
('aespa', 'aespa', 'aespa', NULL, NULL, NULL, 5),
('NewJeans', 'NewJeans', 'NewJeans', NULL, NULL, NULL, 6),
('TWICE', 'TWICE', 'TWICE', NULL, NULL, NULL, 7),
('Stray Kids', 'Stray Kids', 'Stray Kids', NULL, NULL, NULL, 8),
('EXO', 'EXO', 'EXO', NULL, NULL, NULL, 9),
('NCT', 'NCT', 'NCT', NULL, NULL, NULL, 10),
('ATEEZ', 'ATEEZ', 'ATEEZ', NULL, NULL, NULL, 11),
('LE SSERAFIM', 'LE SSERAFIM', 'LE SSERAFIM', NULL, NULL, NULL, 12),
('아이유(IU)', '아이유(IU)', '아이유(IU)', NULL, NULL, NULL, 13),
('태연(Taeyeon)', '태연(Taeyeon)', '태연(Taeyeon)', NULL, NULL, NULL, 14),
('임영웅', '임영웅', '임영웅', NULL, NULL, NULL, 15),
('지코(ZICO)', '지코(ZICO)', '지코(ZICO)', NULL, NULL, NULL, 16),
('악뮤(AKMU)', '악뮤(AKMU)', '악뮤(AKMU)', NULL, NULL, NULL, 17),
('DAY6', 'DAY6', 'DAY6', NULL, NULL, NULL, 18),
('(여자)아이들', '(여자)아이들', '(여자)아이들', NULL, NULL, NULL, 19),
('RIIZE', 'RIIZE', 'RIIZE', NULL, NULL, NULL, 20),
('BOYNEXTDOOR', 'BOYNEXTDOOR', 'BOYNEXTDOOR', NULL, NULL, NULL, 21),
('TOMORROW X TOGETHER', 'TOMORROW X TOGETHER', 'TOMORROW X TOGETHER', NULL, NULL, NULL, 22),
('ENHYPEN', 'ENHYPEN', 'ENHYPEN', NULL, NULL, NULL, 23),
('Red Velvet', 'Red Velvet', 'Red Velvet', NULL, NULL, NULL, 24),
('ITZY', 'ITZY', 'ITZY', NULL, NULL, NULL, 25),
('에스파(aespa)', '에스파(aespa)', '에스파(aespa)', NULL, NULL, NULL, 26),
('G-DRAGON', 'G-DRAGON', 'G-DRAGON', NULL, NULL, NULL, 27),
('박효신', '박효신', '박효신', NULL, NULL, NULL, 28),
('이무진', '이무진', '이무진', NULL, NULL, NULL, 29),
('볼빨간사춘기', '볼빨간사춘기', '볼빨간사춘기', NULL, NULL, NULL, 30),
('백예린', '백예린', '백예린', NULL, NULL, NULL, 31),
('성시경', '성시경', '성시경', NULL, NULL, NULL, 32),
('장원영', '장원영', '장원영', NULL, NULL, NULL, 33),
('차은우', '차은우', '차은우', NULL, NULL, NULL, 34),
('유재석', '유재석', '유재석', NULL, NULL, NULL, 35),
('침착맨', '침착맨', '침착맨', NULL, NULL, NULL, 36),
('쯔양', '쯔양', '쯔양', NULL, NULL, NULL, 37),
('곽튜브', '곽튜브', '곽튜브', NULL, NULL, NULL, 38),
('빠니보틀', '빠니보틀', '빠니보틀', NULL, NULL, NULL, 39),
('감스트', '감스트', '감스트', NULL, NULL, NULL, 40),
('이영지', '이영지', '이영지', NULL, NULL, NULL, 41),
('혜안', '혜안', '혜안', NULL, NULL, NULL, 42),
('원지의하루', '원지의하루', '원지의하루', NULL, NULL, NULL, 43),
('피식대학', '피식대학', '피식대학', NULL, NULL, NULL, 44),
('숏박스', '숏박스', '숏박스', NULL, NULL, NULL, 45),
('문복희', '문복희', '문복희', NULL, NULL, NULL, 46),
('입짧은햇님', '입짧은햇님', '입짧은햇님', NULL, NULL, NULL, 47),
('워크맨', '워크맨', '워크맨', NULL, NULL, NULL, 48),
('딩고뮤직', '딩고뮤직', '딩고뮤직', NULL, NULL, NULL, 49)
ON CONFLICT (slug) DO UPDATE SET
    name_ko = EXCLUDED.name_ko,
    name_en = EXCLUDED.name_en,
    profile = EXCLUDED.profile,
    image_url = EXCLUDED.image_url,
    official_url = EXCLUDED.official_url,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();