export const SCREEN_MAP: Record<string, string> = {
    "/": "MAIN_PAGE",
    "/MAIN_PAGE": "MAIN_PAGE",
    "/LOGIN_PAGE": "LOGIN_PAGE",
    "/SET_TIME_PAGE": "SET_TIME_PAGE" ,
    "/TUTORIAL_PAGE" : "TUTORIAL_PAGE",
    "/CONTENT_LIST": "CONTENT_LIST",
    "/CONTENT_WRITE": "CONTENT_WRITE",
    "/CONTENT_DETAIL" : "CONTENT_DETAIL",
    "/CONTENT_MODIFY" : "CONTENT_MODIFY",
    "/COMMUNITY_LIST": "COMMUNITY_LIST",
    "/COMMUNITY_WRITE": "COMMUNITY_WRITE",
    "/COMMUNITY_DETAIL": "COMMUNITY_DETAIL",
    "/COMMUNITY_MODIFY": "COMMUNITY_MODIFY",
    "/MY_PAGE": "MY_PAGE",
    // "/DASHBOARD_PAGE": "DASHBOARD_PAGE",
    "/AI_ENGLISH_CHAT_PAGE": "AI_ENGLISH_CHAT_PAGE",
    "/AI_JAPANESE_CHAT_PAGE": "AI_JAPANESE_CHAT_PAGE",
    "/AI_KOREAN_CHAT_PAGE": "AI_KOREAN_CHAT_PAGE",
    "/MEMBERSHIP_SHOP_PAGE": "MEMBERSHIP_SHOP_PAGE",
    "/GOOGLE_CALLBACK": "GOOGLE_CALLBACK",
    "/ADMIN_DASHBOARD": "ADMIN_DASHBOARD",
    "/THEME_SETTINGS": "THEME_SETTINGS",
};

// 도메인 플러그인이 URL→screenId 매핑을 런타임 주입한다(코어 하드코딩 제거).
// 라우트 청크 평가 시점(렌더 이전)에 호출되어 SCREEN_MAP에 병합된다.
export function registerScreenPaths(paths: Record<string, string>): void {
    Object.assign(SCREEN_MAP, paths);
}

export const DEFAULT_SCREEN_ID = "MAIN_PAGE";
