'use client';
import { FormEvent, useState } from 'react';
import dynamic from 'next/dynamic';
import type { RoadPoint } from './RoadRouteMap';
const RoadRouteMap=dynamic(()=>import('./RoadRouteMap'),{ssr:false});
type Result={path?:RoadPoint[];course?:RoadPoint[];total_distance_km:number;facilities_on_route?:{name:string;type:string;distance_km:number}[];facilities_on_course?:{name:string;type:string;distance_km:number}[];pois_on_route?:{title:string;lat:number;lon:number}[];pois_on_course?:{title:string;lat:number;lon:number}[];courseType?:string};
export default function RoadRoutePlanner(){
 const [weather,setWeather]=useState('');
 const [kind,setKind]=useState('route'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);const body=Object.fromEntries([...form].map(([k,v])=>[k,Number(v)]));setBusy(true);setError('');setResult(null);setWeather('');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);
 try{const response=await fetch('/api/kride/route/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'길 찾기를 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.');if(!(data.path??data.course)?.length)throw new Error('조건에 맞는 경로가 없습니다.');setResult(data);try{const w=await fetch('/api/kride/route/weather?lat='+body.start_lat+'&lon='+body.start_lon,{signal:controller.signal});const info=await w.json();setWeather(w.ok?(info.fallback?'실시간 날씨 확인 불가 · 기본값 사용':info.weather_label):'날씨 확인 불가');}catch{setWeather('날씨 확인 불가');}}
 catch(e){setError(e instanceof Error&&e.name==='AbortError'?'30초 안에 응답하지 않았습니다. 다시 시도해 주세요.':e instanceof Error?e.message:'경로 조회 실패');}finally{clearTimeout(timer);setBusy(false);}}
 return <section aria-label="도로 길 찾기" style={{padding:18,border:'1px solid #ddd',borderRadius:12,fontSize:16,lineHeight:1.65}}><h2 style={{fontSize:22,fontWeight:700,marginBottom:8}}>서울 도로 길 찾기</h2><p>지원 도로에서 2km 이내의 좌표를 입력하세요. 왕복 코스는 같은 길로 출발점에 돌아옵니다.</p>
 <form onSubmit={submit}><label>경로 종류 <select style={{padding:10,border:'1px solid #a8b3c2',borderRadius:8,minHeight:44,background:'white'}} value={kind} disabled={busy} onChange={e=>{setKind(e.target.value);setResult(null);setError('');}}><option value="route">출발 → 도착</option><option value="course">왕복 코스</option></select></label>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:12,margin:'16px 0'}}>{[['start_lat','출발 위도',-90,90],['start_lon','출발 경도',-180,180],...(kind==='route'?[['end_lat','도착 위도',-90,90],['end_lon','도착 경도',-180,180]]:[['distance_km','왕복 거리(km)',.2,50]])].map(([name,label,min,max])=><label key={name}>{label}<input style={{display:'block',width:'100%',boxSizing:'border-box',padding:10,border:'1px solid #a8b3c2',borderRadius:8,minHeight:44,background:'white',marginTop:4}} name={String(name)} type="number" step="any" min={Number(min)} max={Number(max)} required disabled={busy}/></label>)}</div><button style={{padding:'10px 20px',minHeight:44,borderRadius:8,border:0,background:busy?'#64748b':'#b91c1c',color:'white',cursor:busy?'wait':'pointer'}} disabled={busy}>{busy?'경로 계산 중…':'길 찾기'}</button></form>
 {error&&<p role="alert">{error}</p>}{result&&<><p role="status">{weather && <span>{weather} · </span>}{result.total_distance_km}km · {result.courseType?'출발점으로 돌아오는 왕복 코스':'출발·도착 경로'}</p><RoadRouteMap points={result.path??result.course??[]} pois={result.pois_on_route??result.pois_on_course??[]}/><ul>{(result.facilities_on_route??result.facilities_on_course??[]).map((f,i)=><li key={i}>{f.name || '이름 미등록 시설'} · {f.type || '분류 미등록'} · 경로에서 {f.distance_km}km</li>)}</ul><p>경로 주변 시설 {(result.facilities_on_route??result.facilities_on_course??[]).length}개 · 장소 {(result.pois_on_route??result.pois_on_course??[]).length}개</p></>}
 </section>;
}
