from pathlib import Path
import json,hashlib,collections,datetime,html,csv,ast
W=Path(__file__).parent;W.mkdir(parents=True,exist_ok=True);S=W.parent/'source-linkage-20261007';E=html.escape
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(n,x): (W/n).write_text(json.dumps(x,ensure_ascii=False,indent=2),encoding='utf-8')
r=read(S/'independent-review.json')
for p,h in r['inputSha256'].items():assert sha(Path(p))==h,p
gpath=Path('D:/KMovement/models/kride_graph.json');ghash=sha(gpath);g=read(gpath);places={p['id']:p for p in g['nodes'] if p['type']=='POI'}
csvhash=sha(S/'official-media.csv')
ledger=[json.loads(s) for s in (S/'place-linkage-local.jsonl').read_text(encoding='utf-8').splitlines()]
approved={x['legacyId']:x for x in r['rows'] if x['identityDecision']=='approved-for-facility-identity-crosswalk-only'}
catalog=read(W.parent/'independent-review-20261007/places11-source-freeze-v1/catalog-11-v1.json');canon={p['id']:p for p in catalog['items']}
rules={'version':'public-place-candidate-v1','scope':'dated basic place metadata preparation, NOT service-publication approval','precedence':['existing independently approved identity + no location flags -> data_pass','unresolved duplicate or coordinate/address flag -> human_review','official exact name/address, all matched coordinates within100m, no duplicate/flags -> data_pass','otherwise -> auto_hold_missing_source'],'sourceAge':'2022 source is historical; current existence/hours/price/artist not certified','multilingual':'only independently approved KO/EN/JA names','canonicalization':'only approved curated identity links; no other merges','searchVerifiedCount':None,'servicePublicApprovedFromThisTask':0,'executionAllowed':False}
save('rules-v1.json',rules)
classified=[];candidates={}
for x in ledger:
 p=places[x['id']];a=approved.get(x['id']);flags=list(x['reviewFlags'])
 if a and not flags:status='data_pass';reason='independent_identity_evidence'
 elif flags or x['duplicateGroup']:status='human_review';reason='location_or_duplicate_review'
 elif x['officialSourceStatus']=='exact-name-address-coordinates-within-100m':status='data_pass';reason='historical_official_row_match'
 else:status='auto_hold';reason='missing_linked_official_source'
 cid=a['canonicalId'] if a else x['id']
 classified.append({'legacyId':x['id'],'candidateId':cid,'status':status,'reason':reason,'flags':flags,'duplicateGroup':x['duplicateGroup'],'serviceEligible':False})
 if status!='data_pass':continue
 if cid in candidates:candidates[cid]['legacyIds'].append(x['id']);continue
 if a:
  c=canon[cid];names={k:v['value'] for k,v in c['names'].items()};sources=[{'url':v['sourceUrl'],'sha256':v['sourceSha256'],'locator':v.get('locator'),'language':k} for k,v in c['names'].items()];address=c['address'];lat=c['lat'];lon=c['lon'];updated=c['verifiedAt'];level='independent_multilingual_identity'
 else:
  names={'ko':p['name'],'en':None,'ja':None};sources=[{'url':'https://www.data.go.kr/data/15111405/fileData.do','sha256':csvhash,'csvRecords':[z['csvRecord'] for z in x['officialCsvRows']]}];address=p.get('address');lat=p['lat'];lon=p['lon'];updated=sorted(set(z['sourceUpdatedAt'] for z in x['officialCsvRows']));level='historical_official_match'
 candidates[cid]={'id':cid,'legacyIds':[x['id']],'names':names,'address':address,'lat':lat,'lon':lon,'evidenceLevel':level,'sourceDate':updated,'sources':sources,'coordinateStatus':'reviewed official marker; entrance accuracy unverified' if a else 'legacy coordinate within100m of matched historical rows; not verified entrance','officialCoordinateEvidence':[] if a else [{'lat':z['lat'],'lon':z['lon'],'csvRecord':z['csvRecord']} for z in x['officialCsvRows']],'allowedClaims':['source-dated place name/address','coordinate only with provenance and uncertainty'],'unsupported':['current opening/existence','price','artist visit/relation','budget guarantee'],'multilingualReady':bool(a),'searchValidated':False,'serviceEligible':False,'remainingGates':['current source recheck','retrieval evaluation','answer refusal and over-refusal','performance','login stop retry acceptance']}
counts=dict(collections.Counter(x['status'] for x in classified));cs=list(candidates.values());mult=[x for x in cs if x['multilingualReady']]
assert sum(counts.values())==40664 and len(classified)==len({x['legacyId'] for x in classified})
assert len(mult)==4 and all(not x['serviceEligible'] for x in cs)
assert sha(gpath)==ghash
summary={'checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'storedRows':40664,'searchVerifiedCount':None,'servicePublicApprovedFromThisTask':0,'existingServicePublicCount':'not rechecked','classificationRows':counts,'candidateEntities':len(cs),'independentMultilingualEntities':len(mult),'approvedAliasRowsCollapsedInDerivedSet':counts['data_pass']-len(cs),'sourceGraphSha256':ghash,'sourceGraphUnchanged':True,'classificationDisjointAndComplete':True,'originalDeletedOrEdited':False,'searchExecuted':False,'deployed':False,'inputHashes':{n:sha(S/n) for n in ['place-linkage-local.jsonl','independent-review.json','linkage-result.json']}}
save('summary.json',summary);save('public-preparation-candidates.json',cs);save('multilingual-candidates.json',mult);save('service-approved-set.json',{'scope':'new approvals from this task only; not existing service inventory','places':[],'reason':'service acceptance gates pending'})
with (W/'classification-local.jsonl').open('w',encoding='utf-8') as f:
 for x in classified:f.write(json.dumps(x,ensure_ascii=False)+'\n')
cols=['id','name_ko','name_en','name_ja','address','latitude','longitude','evidence_level','official_source','service_eligible']
with (W/'places-only.csv').open('w',encoding='utf-8-sig',newline='') as f:
 w=csv.writer(f);w.writerow(cols)
 for x in cs:
  vals=[x['id'],x['names']['ko'],x['names']['en'] or '미확인',x['names']['ja'] or '미확인',x['address'],x['lat'],x['lon'],x['evidenceLevel'],x['sources'][0]['url'],'false'];w.writerow([("'"+v if v.startswith(('=','+','-','@')) else v) if isinstance(v,str) else v for v in vals])
stamp=datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))).strftime('%Y%m%d-%H%M%S');prefix=f'docs/2026-10-07/public-place-set-{stamp[-6:]}'
base=ast.parse((W.parent/'live-response-20261007/build-report.py').read_text(encoding='utf-8'));css=next(ast.literal_eval(n.value) for n in base.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='css' for t in n.targets))
t=(W.parent/'full-catalog-plan-20261007/build.py').read_text(encoding='utf-8');js=t.split('js="""',1)[1].split('""".replace',1)[0]
sections=[('1. 전체와 공개를 나눴습니다',f'전체 저장 40,664개 기록입니다. 실제 검색 가능한 개수는 아직 미확정입니다. 이번 작업에서 서비스 공개를 새로 승인한 장소는 0개입니다. 이는 현재 서비스에 장소가 0개라는 뜻은 아닙니다.'),('2. 자동 통과',f"공개 준비 자료 요건 통과는 {counts['data_pass']:,}개 기록이며, 이미 동일 장소로 검수된 중복 연결만 묶으면 {len(cs):,}개 후보입니다. 이 수는 후보 ID 기준이며, 실제 시설의 중복이 모두 제거됐다는 뜻은 아닙니다. 이 중 한·영·일 이름과 동일 장소를 독립 검수한 것은 4곳입니다. 나머지는 과거 공식 자료의 이름·주소·좌표 대응 조건을 통과한 후보입니다."),('3. 자동 보류',f"공식 출처가 아직 연결되지 않은 {counts['auto_hold']:,}개 기록은 자동 보류했습니다. 자료가 없거나 장소가 사라졌다는 뜻은 아닙니다. 원래 제공자의 자료를 묶음으로 연결해 다시 판정하면 되므로 전부 사람이 하나씩 확인할 필요는 없습니다."),('4. 사람 확인 필요',f"중복이나 주소·좌표 검토가 남은 {counts['human_review']:,}개 기록을 분리했습니다. 3,313개 중복 묶음·주소좌표 보완 1,472개·공식 좌표 차이42개는 서로 겹칩니다. 합산하지 않고 장소 ID별로 한 번만 분류했습니다. 사람은 충돌 사례와 표본 검수에 집중할 수 있습니다."),('5. 장소만 모은 목록','장소 전용 문서에서 이름·주소·공식 출처와 다국어 검수 여부를 확인할 수 있습니다. 영어·일본어 이름이 없는 곳은 미확인으로 표시했습니다. 과거 촬영지 자료의 수집일은 현재 영업을 보장하지 않습니다. 가격·아티스트 방문·예산 적합성도 미확인입니다.'),('6. 다음 통과 기준','다음 단계는 후보 목록의 최신 공식 근거 재확인과 별도 검색·답변·성능·로그인 검증입니다. 그 결과를 통과한 장소만 서비스 공개 목록으로 옮깁니다. 이번에는 목록과 분류 문서만 만들었고 원본 수정·검색 구축·실제 검색·운영 배포는 하지 않았습니다.')]
fix=[(h,p) for h,p in sections];fix[1]=(fix[1][0],fix[1][1]+' rules-v1.json의 우선순위는 독립 identity 승인+위치 flag없음 → data_pass, unresolved duplicate/위치flag → human_review, 공식 exact name/address+모든 대응좌표≤100m+중복없음 → data_pass, 나머지 auto_hold다. 100m는 기존 triage 기준이며 현장 동일성 증명이 아니다.');fix[4]=(fix[4][0],fix[4][1]+' classification-local.jsonl은 원본 ID 전량 판정, public-preparation-candidates.json은 출처 SHA/행번호/허용 주장/금지 주장/잔여 gate를 보존한다. service-approved-set.json은 이번 신규 승인만 나타내는 빈 집합이다. 파생 집합의 canonical ID 통합은 이전 독립 검수된 연결만 사용하고 원본 ID는 legacyIds로 전부 남긴다.')
paths={}
for kind,sec in [('easy-guide',sections),('fix-guide',fix),('work-map',sections)]:
 title={'easy-guide':'공개 준비 장소 집합 · 세 가지 검수 결과','fix-guide':'장소 집합 판정 규칙과 공개 전 검증','work-map':'저장 → 자료 분류 → 후보 → 서비스 검증'}[kind]
 (W/(kind+'.md')).write_text('# '+title+'\n\n'+ '\n\n'.join('## '+h+'\n\n'+p for h,p in sec),encoding='utf-8')
 nodes=[(str(i),h,p) for i,(h,p) in enumerate(sec)];nav=' → '.join(f'<button data-node="{i}">{E(h)}</button>' for i,h,p in nodes);tabs=''.join(f'<button role="tab" id="tab-{i}" aria-controls="{i}" aria-selected="{str(i=="map").lower()}" tabindex="{0 if i=="map" else -1}" data-tab="{i}">{l}</button>' for i,l in [('map','작업 지도'),('report','보고서'),('compare','Before / After')]);diagram='<div class="diagram">'+''.join(f'<button data-node="{i}">{E(h)}</button>' for i,h,p in nodes)+'</div>';script=js.replace('DATA',json.dumps(nodes,ensure_ascii=False).replace('<','\\u003c'));report=''.join(f'<article><h2>{E(h)}</h2><p>{E(p)}</p></article>' for h,p in sec)
 out=f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>{css}</style></head><body><div class="goal">목표: 전량을 자동 분류하고 공개 준비 장소를 별도로 모은다.</div><main><header><h1>{title}</h1><p>현재 위치: 공개 장소 준비 / 자료 요건 분류 완료 · 서비스 승인 미완료</p><ol><li>전체 40,664개를 빠짐없이 세 범주로 나눴습니다.</li><li>자료 통과 후보 {len(cs):,}곳 중 다국어 검수는4곳입니다.</li><li>검색 가능 수는 미확정이며 이번 신규 공개 승인은0곳입니다.</li></ol><p>다음 행동: 후보의 최신 근거와 서비스 검증을 진행합니다.</p><p>확인한 것: 원본 보존·전량 분류·후보 목록. 아직 모르는 것: 실제 검색 및 서비스 수용 검사 결과.</p></header><nav class="flow">{nav}</nav><nav class="tabs" role="tablist">{tabs}</nav><section id="map" role="tabpanel" aria-labelledby="tab-map"><div class="layout"><article><h2 id="node-title" tabindex="-1">{E(nodes[0][1])}</h2><p id="node-body">{E(nodes[0][2])}</p></article>{diagram}</div></section><section id="report" role="tabpanel" aria-labelledby="tab-report" hidden>{report}</section><section id="compare" role="tabpanel" aria-labelledby="tab-compare" hidden><article><h2>Before / After — 데이터 상태 비교 모형</h2><div class="compare"><div class="mock"><h3>이전</h3><p>전량40,664 · 출처/중복/위치 검토 기록</p><p>서비스용 후보 집합 미분리</p></div><div class="mock"><h3>현재</h3><p>자료 자동 통과 {counts['data_pass']:,}개 기록</p><p>자동 보류 {counts['auto_hold']:,}개 기록</p><p>사람 확인 {counts['human_review']:,}개 기록</p><p>자료 통과 후보 {len(cs):,}곳 / 서비스 승인0</p></div></div><p>실제 서비스 화면이 아닌 목록 생성 전후의 비교입니다.</p></article></section></main><script>{script}</script></body></html>'''
 path=W.parents[1]/f'{kind}-{stamp}-public-place-set.html';path.write_text(out,encoding='utf-8');paths[kind]=str(path)
md=['# 장소 집합만 보기 — 공개 준비 후보','',f'총 {len(cs)}개 후보. 서비스 승인 목록이 아닙니다. 현재 영업·가격·아티스트 관계 미확인. 검색 검증 미실행.','', '| 장소 | 주소 | 영어 | 일본어 | 근거 |','|---|---|---|---|---|']
cards=[]
for x in cs:
 vals=[x['names']['ko'],x['address'],x['names']['en'] or '미확인',x['names']['ja'] or '미확인'];md.append('| '+' | '.join(str(v).replace('|','\\|').replace('\n',' ') for v in vals)+' | [공식 출처]('+x['sources'][0]['url']+') |')
 cards.append('<article data-multi="'+str(x['multilingualReady']).lower()+'"><h2>'+E(vals[0])+'</h2><p>'+E(vals[1])+'</p><p>'+E(vals[2])+' · '+E(vals[3])+'</p><p>'+E(x['id'])+' · '+('다국어 독립 검수' if x['multilingualReady'] else '과거 공식 자료 대응')+'</p><a href="'+E(x['sources'][0]['url'],quote=True)+'">공식 출처</a><p>서비스 공개 전 검증 대기</p></article>')
(W/'places-only.md').write_text('\n'.join(md),encoding='utf-8')
ph=W.parents[1]/f'places-only-{stamp}-public-candidates.html'
ph.write_text(f'''<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>장소 목록 · 공개 준비 후보</title><style>body{{font:16px/1.6 system-ui;color:#172638;background:#f4f7fa;margin:24px}}main{{max-width:1100px;margin:auto}}#places{{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:16px}}article{{background:white;padding:20px;border-radius:12px;overflow-wrap:anywhere}}input,select{{font:inherit;padding:12px;max-width:100%;box-sizing:border-box}}[hidden]{{display:none!important}}a{{color:#164a96}}</style></head><body><main><h1>장소 집합만 보기</h1><p>공개 준비 후보 {len(cs):,}곳 · 다국어 독립 검수4곳 · 서비스 신규 승인0곳</p><p>과거 공식 자료 또는 검수된 명칭을 연결한 목록입니다. 현재 영업·가격·아티스트 관계를 보장하지 않습니다.</p><label>장소·주소 찾기 <input id="q" type="search"></label><label>목록 <select id="mode"><option value="all">전체 자료 통과 후보</option><option value="multi">다국어 검수4곳</option></select></label><p id="count" aria-live="polite"></p><div id="places">{''.join(cards)}</div></main><script>const q=document.querySelector('#q'),m=document.querySelector('#mode'),cards=[...document.querySelectorAll('article')];function filter(){{let n=0;for(const c of cards){{c.hidden=!(c.textContent.toLowerCase().includes(q.value.toLowerCase())&&(m.value==='all'||c.dataset.multi==='true'));if(!c.hidden)n++;}}document.querySelector('#count').textContent=n+'곳 표시';}}q.addEventListener('input',filter);m.addEventListener('change',filter);filter();</script></body></html>''',encoding='utf-8')
save('manifest.json',{'paths':paths,'placesHtml':str(ph),'prefix':prefix});save('data-validation.json',{'passed':True,'completeDisjoint40664':True,'sourceInputHashesVerified':True,'noPublicApprovalInferred':True,'graphUnchanged':True});print(json.dumps(summary,ensure_ascii=False));print(ph)
