'use client';

import { FormEvent, useState } from 'react';
import api from '@/services/axios';
import { useAuth } from '@/context/AuthContext';

export default function HolySubmitPage(){const{isLoggedIn,isLoading}=useAuth();const[done,setDone]=useState(false);const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api.post('/api/v1/tour/holy/submissions',{title:f.get('title'),addr:f.get('addr'),artist:f.get('artist'),mapX:Number(f.get('mapX')),mapY:Number(f.get('mapY')),recommendReason:f.get('recommendReason'),sourceUrl:f.get('sourceUrl')});setDone(true)}catch{setError('제보를 저장하지 못했습니다. 입력값과 중복 출처를 확인해 주세요.')}finally{setBusy(false)}};
 if(isLoading)return <main className="min-h-screen p-8">불러오는 중…</main>;if(done)return <main className="min-h-screen bg-[#fff7f7] p-8"><div className="mx-auto max-w-xl rounded-3xl bg-white p-10 text-center shadow-sm"><div className="text-4xl">✓</div><h1 className="mt-4 text-2xl font-bold">제보가 검수 큐에 등록됐습니다</h1><p className="mt-3 text-gray-500">관리자 승인 후 성지 탐색에 공개됩니다.</p></div></main>;
 return <main className="min-h-screen bg-[#fff7f7] px-5 py-8 text-[#15171a]"><form onSubmit={submit} className="mx-auto max-w-2xl rounded-3xl bg-white p-6 shadow-sm md:p-9"><p className="text-sm font-bold tracking-[.16em] text-red-600">KRIDE HOLY PLACE</p><h1 className="mt-2 text-3xl font-bold">팬 성지 제보</h1><p className="mt-3 text-sm leading-6 text-gray-500">공개된 사실 정보와 출처만 등록해 주세요. 사진·기사 본문·팬 창작물은 받지 않습니다.</p>{!isLoggedIn&&<p className="mt-5 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">제출하려면 로그인이 필요합니다. 화면 미리보기와 입력은 가능합니다.</p>}{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-7 grid gap-5 md:grid-cols-2"><Field label="장소명" name="title" required/><Field label="아티스트" name="artist" required/><Field label="주소" name="addr"/><Field label="출처 URL" name="sourceUrl" type="url" required/><Field label="경도 (예: 127.04)" name="mapX" type="number" step="any" required/><Field label="위도 (예: 37.54)" name="mapY" type="number" step="any" required/><label className="md:col-span-2"><span className="text-sm font-bold">추천 이유·확인 가능한 사실</span><textarea name="recommendReason" required maxLength={500} className="mt-2 min-h-32 w-full rounded-xl border border-gray-200 p-3 outline-none focus:border-red-500"/></label></div><button disabled={!isLoggedIn||busy} className="mt-7 w-full rounded-xl bg-red-600 px-5 py-4 font-bold text-white disabled:bg-gray-300">{busy?'등록 중…':'검수 요청하기'}</button></form></main>}
function Field({label,name,type='text',required=false,step}:{label:string;name:string;type?:string;required?:boolean;step?:string}){return <label><span className="text-sm font-bold">{label}</span><input name={name} type={type} required={required} step={step} className="mt-2 h-12 w-full rounded-xl border border-gray-200 px-3 outline-none focus:border-red-500"/></label>}
