 'use client';
import {FormEvent,useEffect,useRef,useState} from 'react';import Link from 'next/link';
import {useAuth} from '@/context/AuthContext';import {consumeChatStream} from '@/lib/kride/consumeChatStream';import type {ScreenControllerProps} from './types';
type Message={role:'user'|'assistant';content:string};
export default function LanguageChatScreen({screenId}:ScreenControllerProps){
 const language=screenId==='AI_JAPANESE_CHAT_PAGE'?'ja':screenId==='AI_KOREAN_CHAT_PAGE'?'ko':'en';
 const name=language==='ja'?'일본어':language==='ko'?'한국어':'영어';const auth=useAuth();
 const [messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[last,setLast]=useState('');
 const active=useRef<AbortController|null>(null),generation=useRef(0),live=useRef(messages);live.current=messages;
 const stop=()=>{generation.current++;active.current?.abort();active.current=null;setBusy(false)};
 useEffect(()=>{stop();setMessages([]);setError('');setLast('');return()=>{generation.current++;active.current?.abort()}},[language,auth.user?.userSqno]); // eslint-disable-line react-hooks/exhaustive-deps
 const send=async(text:string,retry=false)=>{if(active.current||!text.trim()||!auth.isLoggedIn)return;const controller=new AbortController();active.current=controller;const run=++generation.current;const history=(retry?live.current.slice(0,-2):live.current).filter(m=>m.content).slice(-4);const context=history.length?'Previous conversation:\n'+history.map(m=>m.role+': '+m.content).join('\n').slice(-2000)+'\nCurrent message: ':'';
  setLast(text);setError('');setBusy(true);setMessages([...history,{role:'user',content:text},{role:'assistant',content:''}]);
  try{const r=await fetch('/api/kride/chat/stream',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({message:context+text,language}),signal:controller.signal});await consumeChatStream(r,controller.signal,chunk=>{if(run===generation.current)setMessages(prev=>[...prev.slice(0,-1),{role:'assistant',content:prev[prev.length-1].content+chunk}])});}
  catch(e){if(run===generation.current&&!controller.signal.aborted)setError((e as Error).message)}finally{if(run===generation.current){setBusy(false);active.current=null}}
 };
 const submit=(e:FormEvent)=>{e.preventDefault();const text=input.trim();if(text){setInput('');void send(text)}};
 return <section className="language-chat"><nav className="language-chat-tabs" aria-label="대화 언어"><Link href="/view/AI_ENGLISH_CHAT_PAGE" aria-current={language==='en'?'page':undefined}>영어 채팅</Link><Link href="/view/AI_JAPANESE_CHAT_PAGE" aria-current={language==='ja'?'page':undefined}>일본어 채팅</Link></nav><h1>{name} 채팅</h1><p>텍스트로 대화를 연습하세요. AI가 {name} 답변과 짧은 한국어 설명을 제공합니다.</p>{auth.isLoading?<p role="status">로그인을 확인하는 중…</p>:!auth.isLoggedIn?<div className="kride-empty"><p>로그인 후 대화를 시작할 수 있어요.</p><Link className="kride-primary-button" href={'/view/LOGIN_PAGE?returnTo='+encodeURIComponent('/view/'+screenId)}>로그인하고 시작하기</Link></div>:<><div className="language-thread" role="log" aria-label="대화 내용" aria-busy={busy}>{messages.length===0?<p>질문을 입력해 시작하세요. 예: {language==='ja'?'東京でおすすめの場所は？':'How can I order coffee?'}</p>:messages.map((m,i)=><div key={i} className={'language-message '+m.role}><strong>{m.role==='user'?'나':'AI'}</strong><p>{m.content||'답변을 기다리는 중…'}</p></div>)}</div>{error&&<div role="alert"><p>{error}</p><button disabled={busy} onClick={()=>void send(last,true)}>다시 시도</button></div>}<form className="language-composer" onSubmit={submit}><label htmlFor="language-message">{name} 대화 메시지</label><textarea id="language-message" value={input} maxLength={1500} onChange={e=>setInput(e.target.value)} placeholder="한국어 또는 선택한 언어로 입력하세요."/><div className="language-actions"><button type="submit" disabled={busy||!input.trim()}>전송</button>{busy&&<button type="button" onClick={stop}>응답 중단</button>}<button type="button" onClick={()=>{stop();setMessages([]);setError('');setLast('')}}>대화 종료</button></div></form><p>현재 시험 운영 중입니다. 음성 녹음은 아직 이 화면에서 제공하지 않습니다.</p></>}</section>;
}
